var listTask = [
  {
      key: '24131918',
      taskName: 'I want to go home',
      folderName: 'Misc',
      pomoRound: '0',
      folderColor: 'rgb(255, 153, 0)',
      priorColor: 'red',
      scheduleDate: 'Jan 13th', 
      dateTrans: 'Monday',

  },
  {
      key: '21431516',
      taskName: 'Daily stand up',
      folderName: 'Misc',
      pomoRound: '0',
      folderColor: 'rgb(255, 153, 0)',
      priorColor: 'blue',
      scheduleDate: 'Jan 9th', 
      dateTrans: 'Thursday',
  },
  {
      key: '24131918',
      taskName: 'Buy icecream',
      folderName: 'Misc',
      pomoRound: '0',
      folderColor: 'rgb(255, 153, 0)',
      priorColor: 'gray',
      scheduleDate: 'Jan 13th', 
      dateTrans: 'Monday',

  },
  {
      key: '21431516',
      taskName: 'Write NLP paper',
      folderName: 'NLP',
      pomoRound: '10',
      folderColor: 'green',
      priorColor: 'red',
      scheduleDate: 'Jan 15th', 
      dateTrans: 'Wednesday',
  },
  {
      key: '24131918',
      taskName: 'Write report CS300',
      folderName: 'CS300',
      pomoRound: '0',
      folderColor: 'rgb(191, 81, 154)',
      priorColor: 'red',
      scheduleDate: 'Jan 15th', 
      dateTrans: 'Wednesday',

  },
  {
      key: '21431516',
      taskName: 'Weep the floor',
      folderName: 'Misc',
      pomoRound: '0',
      folderColor: 'rgb(255, 153, 0)',
      priorColor: 'gray',
      scheduleDate: 'Jan 9th', 
      dateTrans: 'Thursday',
  },
  {
      key: '11351509',
      taskName: 'Do exercise 2',
      folderName: 'Coder school',
      pomoRound: '3',
      folderColor: 'rgb(214, 34, 34)',
      priorColor: 'blue',
      scheduleDate: 'Jan 10th', 
      dateTrans: 'Friday',
  },
  {
      key: '11538519',
      taskName: 'Go to supermarket and buy a towel',
      folderName: 'Misc',
      pomoRound: '0',
      folderColor: 'rgb(255, 153, 0)',
      priorColor: 'blue',
      scheduleDate: 'Jan 10th', 
      dateTrans: 'Friday',
  },
  
];

module.exports = listTask;